import { Category } from '@/types/marketplace';

export const categories: Category[] = [
  {
    id: '1',
    name: 'Car Services',
    icon: 'car',
    color: '#3B82F6',
    subCategories: [
      { id: '101', name: 'Flat Tire', icon: 'tool' },
      { id: '102', name: 'Jump Start', icon: 'battery-charging' },
      { id: '103', name: 'Towing', icon: 'truck' },
      { id: '104', name: 'Oil Change', icon: 'droplet' },
      { id: '105', name: 'Carwash', icon: 'droplets' },
      { id: '106', name: 'Car Detailing', icon: 'sparkles' },
    ],
  },
  {
    id: '2',
    name: 'Home Services',
    icon: 'home',
    color: '#10B981',
    subCategories: [
      { id: '201', name: 'Cleaning', icon: 'spray-can' },
      { id: '202', name: 'Plumbing', icon: 'droplet' },
      { id: '203', name: 'Electrical', icon: 'zap' },
      { id: '204', name: 'Gardening', icon: 'scissors' },
      { id: '205', name: 'General Handyman', icon: 'hammer' },
      { id: '206', name: 'Painter', icon: 'paintbrush' },
      { id: '207', name: 'Appliance Repair', icon: 'wrench' },
      { id: '208', name: 'HVAC Maintenance', icon: 'wind' },
      { id: '209', name: 'Pest Control', icon: 'bug' },
      { id: '210', name: 'Pool Maintenance', icon: 'waves' },
    ],
  },
  {
    id: '3',
    name: 'Personal Services',
    icon: 'user',
    color: '#8B5CF6',
    subCategories: [
      { id: '301', name: 'Haircut', icon: 'scissors' },
      { id: '302', name: 'Massage', icon: 'heart' },
      { id: '303', name: 'Fitness', icon: 'activity' },
      { id: '304', name: 'Manicure / Pedicure', icon: 'hand' },
      { id: '305', name: 'Makeup Artistry', icon: 'palette' },
    ],
  },
  {
    id: '4',
    name: 'Hopi Taxi',
    icon: 'car',
    color: '#14B8A6',
    subCategories: [
      { id: '401', name: 'Standard Taxi', icon: 'car' },
      { id: '402', name: 'Premium Taxi', icon: 'crown' },
      { id: '403', name: 'XL Taxi', icon: 'truck' },
      { id: '404', name: 'Luxury Taxi', icon: 'gem' },
      { id: '405', name: 'Airport Transfer', icon: 'plane' },
      { id: '406', name: 'Scheduled Ride', icon: 'calendar' },
    ],
  },
  {
    id: '5',
    name: 'Tech Services',
    icon: 'laptop',
    color: '#6366F1',
    subCategories: [
      { id: '501', name: 'Computer / Laptop Repair', icon: 'laptop' },
      { id: '502', name: 'Smartphone / Tablet Repair', icon: 'smartphone' },
      { id: '503', name: 'Wifi Setup', icon: 'wifi' },
      { id: '504', name: 'Printer Installation', icon: 'printer' },
      { id: '505', name: 'Audio / Video Setup', icon: 'speaker' },
    ],
  },
  {
    id: '6',
    name: 'Health Services',
    icon: 'heart-pulse',
    color: '#EF4444',
    subCategories: [
      { id: '601', name: 'Certified Nursing Assistant', icon: 'stethoscope' },
      { id: '602', name: 'Physical Therapy', icon: 'activity' },
      { id: '603', name: 'Home Doctors', icon: 'user-check' },
    ],
  },
  {
    id: '7',
    name: 'Hospitality Services',
    icon: 'utensils',
    color: '#F97316',
    subCategories: [
      { id: '701', name: 'Home Chefs', icon: 'chef-hat' },
      { id: '702', name: 'Bartender', icon: 'wine' },
      { id: '703', name: 'Event Planner', icon: 'calendar-days' },
      { id: '704', name: 'DJ / Musician', icon: 'music' },
      { id: '705', name: 'Photographer / Videographer', icon: 'camera' },
    ],
  },
  {
    id: '8',
    name: 'Business Services',
    icon: 'briefcase',
    color: '#06B6D4',
    subCategories: [
      { id: '801', name: 'Accounting', icon: 'calculator' },
      { id: '802', name: 'Marketing', icon: 'trending-up' },
      { id: '803', name: 'Graphic Design', icon: 'palette' },
      { id: '804', name: 'Legal Consulting', icon: 'scale' },
      { id: '805', name: 'Translation', icon: 'languages' },
      { id: '806', name: 'Financial Advisor', icon: 'dollar-sign' },
    ],
  },
  {
    id: '9',
    name: 'Childcare Services',
    icon: 'baby',
    color: '#EC4899',
    subCategories: [
      { id: '901', name: 'Babysitter', icon: 'baby' },
      { id: '902', name: 'Nanny', icon: 'heart' },
      { id: '903', name: 'Special Needs Aide', icon: 'user-heart' },
      { id: '904', name: 'In-home Tutoring + Care', icon: 'graduation-cap' },
    ],
  },
  {
    id: '10',
    name: 'Tourism Services',
    icon: 'map',
    color: '#F59E0B',
    subCategories: [
      { id: '1001', name: 'Tours', icon: 'map-pin' },
      { id: '1002', name: 'Water Sports', icon: 'anchor' },
      { id: '1003', name: 'Private Transportation', icon: 'navigation' },
    ],
  },
];