// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mswxfxvqlhfqsmckezci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zd3hmeHZxbGhmcXNtY2tlemNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MDkwOTAsImV4cCI6MjA2NjQ4NTA5MH0.rl70EaTd19eZY0ytEpYiDRVWvpl73XpoDzFgcVF2hZs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});